### ISSUE TITLE
rosa v1.2.12 delete operator-roles cmd fails to find cluster (Hosted Control Plane Cluster)

### ISSUE THREAD

**Issue by ryankwilliams** [openshift/rosa#1038]
With ROSA version `1.2.11`, when performing `rosa delete operator-roles --cluster <cluster-id> --mode auto`, it would fetch operator roles for the cluster and even if no operator roles existed, it would exit with exit code 0. Allowing for automation to properly carry on and clean up any `oidc-providers`.

```
[rywillia@t14s ~]$ rosa version
1.2.11
There is a newer release version, please consider updating: https://github.com/openshift/rosa/releases/tag/v1.2.12

[rywillia@t14s ~]$ rosa delete operator-roles --cluster 21euo6l1rors2k4v8saatqm906eu0afi --mode auto
? You are running delete operation from 'staging' environment. Please ensure there are no clusters using these operator roles in the production. Are you sure you want to proceed? Yes
I: Fetching operator roles for the cluster: 21euo6l1rors2k4v8saatqm906eu0afi
I: There are no operator roles to delete for the cluster '21euo6l1rors2k4v8saatqm906eu0afi'
[rywillia@t14s ~]$ echo $?
0
```

With ROSA version `1.2.12`, performing the same command. Results in an error stating no cluster found for the ID.

```
[rywillia@t14s ~]$ ./rosa-linux-amd64 version
1.2.12
Your ROSA CLI is up to date.

[rywillia@t14s ~]$ ./rosa-linux-amd64 delete operator-roles --cluster 21euo6l1rors2k4v8saatqm906eu0afi --mode auto
E: Failed to get cluster '': There is no cluster with identifier or name '21euo6l1rors2k4v8saatqm906eu0afi'
[rywillia@t14s ~]$ echo $?
1
```

Is this system exit 1 and error message the new expected behavior?

**Comment by CastawayEGR** [comment]
Confirming I am seeing the same issue with ROSA CLI v1.2.13 as well. 

Reviewing commits this may have been introduced by commit [dc27332](https://github.com/openshift/rosa/commit/dc27332e283f75a8b6026dfc419cea046ef590e5) when the cluster id lookup behavior was changed.

**Comment by ryankwilliams** [comment]
With the number of new releases, this issue does not look to be reproducible anymore. If it happens again, I will re-open the issue.

/close
