### ISSUE TITLE
inconsistencies in flags between `--cluster` and `--cluster-name`

### ISSUE THREAD

**Issue by scottd018** [openshift/rosa#1044]
### Concern:

Flags between subcommands of the rosa CLI are inconsistent.  For example, the `rosa create cluster` command takes in `--cluster-name` as the flag input to specify the cluster name  However, most other commands take in `--cluster` as the flag input to specify the cluster name.

`rosa create cluster -h`:

```bash
-c, --cluster-name string                   Name of the cluster. This will be used when generating a sub-domain for your cluster on openshiftapps.com.
```

`rosa create admin -h`:

```bash
-c, --cluster string    Name or ID of the cluster.
```

#### Info

- Most subcommands use `--cluster` as the input flag
- The `create cluster` subcommand has special information notating that the cluster-name is used as part of the subdomain

#### Proposed Solution

1. Mark the `--cluster-name` flag as deprecated (https://github.com/openshift/rosa/blob/master/cmd/create/cluster/cmd.go#L180) much like the `--name` flag has been marked as deprecated (https://github.com/openshift/rosa/blob/master/cmd/create/cluster/cmd.go#L179).
2. Use `--cluster` as the flag for input for all subcommands that use `--cluster-name`.  This will make all subcommands use consistent flags.
3. Optionally change the `AddClusterFlag` method (https://github.com/openshift/rosa/blob/master/pkg/ocm/flag.go#L41) to something similar to this and use where necessary (e.g. create/delete/etc subcommands) to reduce duplication of code:

```go
func AddClusterFlag(cmd *cobra.Command) {
        AddClusterFlagWithDescription(
                cmd,
                "Name or ID of the cluster.",
                &clusterKey,
        )
}

func AddClusterFlagWithDescription(cmd *cobra.Command, description string, key *string) {
	cmd.Flags().StringVarP(
		key,
		"cluster",
		"c",
		"",
		description,
	)
	cmd.MarkFlagRequired("cluster")
	cmd.RegisterFlagCompletionFunc("cluster", clusterCompletion)
}
```

**Comment by paulczar** [comment]
https://github.com/openshift/rosa/issues/327
