### ISSUE TITLE
Enforcing JIRA references is hostile to external contributors

### ISSUE THREAD

**Issue by cben** [openshift/rosa#1647]
CONTRIBUTING.md says:

> Communicate your intent in the form of a JIRA ticket on the https://issues.redhat.com/projects/OCM project.
> ...
> The commit message should follow this template:
> ```shell
> <type>[JIRA-TICKET] | [TYPE]: <MESSAGE>
> 
> [optional BODY]
>  
> [optional FOOTER(s)]
> ```

And the presence of jira ticket reference is enforced by CI (hack/commit-msg-verify.sh).

But the OCM project is not public.  This means an external community contributor has no way to follow the flow (as documented), nor a way to make a PR that would pass CI :crying_cat_face:

**Comment by thomasmckay** [comment]
Thanks for bring this up @cben . I will inquire internally for the reason and see if we can open it to allow viewing w/o logging in.
