### ISSUE TITLE
SCP region restriction on AWS account is not allowing to validate SCP policies

### ISSUE THREAD

**Issue by harshagadham** [openshift/rosa#224]
Hi,

We have SCP policies setup on AWS account which allows us to deploy resource and restricted to specific region (say we are allowed to deploy resources only to ap-southeast-2 - Sydney region). I see in initialise/cmd.go check for simulate-principal-proxy is called at the time of validating SCP policies. Even though there are no restrictions on Sydney region around what AWS resource we create, when I run rosa init --region=ap-southeast-2 gives error saying Unable to validate SCP policies. Actions not allowed with tested credentials [ec2:* autoscaling:* elasticloadbalancing:* ..]

I see similar issue was resolved on ISI and UPI installer in the past https://bugzilla.redhat.com/show_bug.cgi?id=1757244

Could you please advice on this issue ?

**Comment by harshagadham** [comment]
Also, based on this article https://github.com/openshift/installer/issues/4048 it is advised not to simulate-policy restriction
https://github.com/openshift/installer/issues/4048

**Comment by scottdonaldau** [comment]
/remove-lifecycle stale

This is impacting us in deploying ROSA. Our guardrails have restrictions on some resources specific to the account guardrails which will have no impact on deploying ROSA resources.

**Comment by vkareh** [comment]
Does https://github.com/openshift/rosa/pull/328 fix your issue? It should be available as part of the v1.0.5 release. Otherwise, do you have the error output when you run the command?
