### ISSUE TITLE
Cluster creation failed - 'create_moa_clusters' capability is not set for this account

### ISSUE THREAD

**Issue by ruzickap** [openshift/rosa#242]
Hello guys.

I'm trying to "init" my AWS environment using `rosa` client, but I'm getting this error:

```bash
❯ rosa init --region us-east-1
I: Logged in as 'petr_ruzicka@<email>.com' on 'https://api.openshift.com'
I: Validating AWS credentials...
I: AWS credentials are valid!
I: Validating SCP policies...
I: AWS SCP policies ok
I: Validating AWS quota...
I: AWS quota ok
I: Ensuring cluster administrator user 'osdCcsAdmin'...
I: Admin user 'osdCcsAdmin' already exists!
I: Validating SCP policies for 'osdCcsAdmin'...
I: AWS SCP policies ok
I: Validating cluster creation...
W: Cluster creation failed. If you create a cluster, it should fail with the following error:
'create_moa_clusters' capability is not set for this account
I: Verifying whether OpenShift command-line tool is available...
I: Current OpenShift Client Version: 4.6.16
``` 

The error `'create_moa_clusters' capability is not set for this account` may be more descriptive, because it's not saying if the problem is with AWS account / RedHat account (or somewhere else).

I'm not sure how may I fix this.

Thank you...

**Comment by wgordon17** [comment]
Hi @ruzickap, the error that you're receiving is because Red Hat OpenShift Service on AWS (ROSA) has not officially launched yet. There is an access request form that you can fill out: https://pages.awscloud.com/ROSA_Preview.html. Until ROSA fully launches, the `capability` called out in the error message prevents customers from deploying ROSA clusters unless they have been allow-listed through the preview program.

**Comment by ruzickap** [comment]
Thank you...

Actually I would prefer some "Human understandable" explanation than:

```
W: Cluster creation failed. If you create a cluster, it should fail with the following error:
'create_moa_clusters' capability is not set for this account
```

Thanks...

**Comment by wgordon17** [comment]
ROSA is GA now, I'm closing this issue since this error message should no longer be encountered.
