### ISSUE TITLE
Support for G6 instances

### ISSUE THREAD

**Issue by mooperd** [openshift/rosa#2558]
Hello,

It seems I cant use g6 instances with L4 GPUs in ROSA. Are these on the roadmap?

Cheers,

Andrew

**Comment by hunterkepley** [comment]
Hey @mooperd !

We are currently testing these instance types and are hoping to get them in within the next 2-4 weeks

Best regards,
- Hunter K

**Comment by hunterkepley** [comment]
Let me know if there are other questions, or if we can close this issue 😄

**Comment by mooperd** [comment]
Thanks @hunterkepley
