### ISSUE TITLE
Failed to get user from AWS client when running rosa CLI using AWS Federated Authentication with ADFS

### ISSUE THREAD

**Issue by radarlui** [openshift/rosa#302]
When running the commands rosa whoami or rosa verify permissions using AWS Federated Authentication with ADFS, the following error occur.

>rosa whoami
ERR: failed to create AWS client: ValidationError: Must specify userName when calling with non-User credentials

**Comment by vkareh** [comment]
@radarlui - currently ROSA only supports IAM users. We'll make sure to add this to the official documentation.

**Comment by jharrington22** [comment]
@radarlui yes the credentials you are trying to user are temporary STS credentials federated against ADFS. We recently updated the error returned to the user in [PR 313](https://github.com/openshift/rosa/pull/313) to make it more helpful, if this is sufficient please close the issue. Thanks!

**Comment by radarlui** [comment]
Thanks @jharrington22 for your update. Will STS credentials be supported in the coming release?

**Comment by theofpa** [comment]
Same applies when using Okta as the identity provider, looking forward to getting support for federated authentication!

**Comment by acathrow** [comment]
When using STS an IAM user is no longer required.

**Comment by theofpa** [comment]
fixed by #351
