### ISSUE TITLE
Many cluster-name-tagged t2.micro instances generated during cluster creation - AWS Anomaly triggered

### ISSUE THREAD

**Issue by cloudbustinguk** [openshift/rosa#317]
Hi all,

Despite the convoluted title, I wanted to summarise that AWS Customer Support contacted me at about the same time that a ROSA cluster was being created yesterday. I had enabled multiple availability zones during the interactive installer. Around 15-20 mins into cluster install, I got the call, mentioning they think the account had been compromised due to many (10) t2.micro instances being spawned in quick succession, in different regions.

Many t2.micro instances (short-lived by the looks of it, although I did authorise customer support to terminate them - sadly I didn't get a chance to take a snapshot for post-mortem) were spawned, in many worldwide regions (so, not just multi AZ it seems). The instance tags did include the clustername and ID, so I guess this was just ROSA (or CloudFormation?) ensuring I had validation in other regions, hence why it put in for a t2.micro and nothing larger (as I would expect of, say, a cryptominer).

Have confirmed the account was not compromised, and have also dug through the `rosa` source code, but can't find any mention of this being needed.

Any light you could shed would be great - maybe AWS Support didn't receive the ROSA memo yet?

Cheers
Dan

**Comment by vkareh** [comment]
Hi @cloudbustinguk - This is part of the [AWS Account Operator](https://github.com/openshift/aws-account-operator) and is done to ensure that the regions are enabled and that EC2 instances can be created in it. The t2.micro instances should have been terminated immediately once there is an instance ID available.

@jharrington22 - can you confirm this is information is correct?

**Comment by cloudbustinguk** [comment]
Hi @vkareh - Many thanks for the clarification. I did suspect something along these lines - will have a peek into the guts of the operator.

**Comment by cloudbustinguk** [comment]
Happy to close this. Thanks for your help.

**Comment by jharrington22** [comment]
@cloudbustinguk yes we use the instances to ensure the target AWS account is ready to create a new cluster. The reason that we don't use DryRun parameter when creating these instances is we need to trigger a billing event. A new AWS account will actually receive an error from the AWS API on the first call, we wait until this successful, terminate the instance immediately and continue. Its a very minor charge. Let me know if you have more questions.
