### ISSUE TITLE
inconsistent flag for cluster name between create and other commands.

### ISSUE THREAD

**Issue by paulczar** [openshift/rosa#327]
The command to create a cluster is `rosa create cluster --cluster-name=foo`

The command to delete a cluster is `rosa delete cluster --cluster=foo`

Similarly the `--cluster` flag is used for every command I can find other than create.

Rosa should have consistency in the command flags, i.e. I would suggest updating create to use `--cluster` (and alias --cluster-create` to it for backwards compatibility).

**Comment by vkareh** [comment]
@paulczar - the inconsistency is on purpose. When creating a cluster, the flag expects the cluster name and nothing else, whereas to identify the cluster in any other case it can accept the cluster name, ID, or external ID.
