### ISSUE TITLE
ROSA doesn't allow oc label nodes

### ISSUE THREAD

**Issue by maulikshah999** [openshift/rosa#333]
The auth webhook prevents node labeling. This is needed to dedicate workloads. The error is:

admission webhook "regular-user-validation.managed.openshift.io" denied the request: Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support

The user does have cluster-admin rights

we have also filed **Red Hat Support case:** https://access.redhat.com/support/cases/#/case/02878398

**Failure:** https://access.redhat.com/support/cases/#/case/02878398/discussion?attachmentId=a092K00002Py7GoQAJ

**Problem:** We can not install **OCS** storage class without labeling in the ROSA cluster.

**Comment by vkareh** [comment]
I don't have access to see the support case, but anything in a `redhat-*` namespace is disallowed from being modified by any external entity. You would need to have the service behind api.openshift.com supply the labels through a syncset, or some configuration in the OCS addon operator.

**Comment by akinfemi** [comment]
You won't be able to label nodes individually, but you can add labels to the machinepool:
```bash
rosa edit machinepool --cluster --label='<key:value>'
```
To install OCS, you can create a new machinepool with the required labels and taints using the rosa binary, then install OCS via the normal operator way (https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.7/html/deploying_openshift_container_storage_using_amazon_web_services/index)

**Comment by maulikshah999** [comment]
Thanks, @akinfemi  and @vkareh for your input. I am closing the issue as Femi's workaround will help us fix the issue.
