### ISSUE TITLE
Do not have parameter --basedomain as exist in openshift-install CLI

### ISSUE THREAD

**Issue by marcelo-change** [openshift/rosa#374]
I'm trying to create a cluster using the ROSA CLI but I can't find any way to set up an OpenShift using my domain on AWS Route 53 as in the openshift-install CLI tool.

`$ rosa create cluster --cluster-name testing --multi-az --region eu-west-1 --version 4.7.16 --enable-autoscaling --min-replicas 3 --max-replicas 6 --compute-machine-type c5.2xlarge`

**VS**

`$ openshift-install create cluster --dir=. --log-level=info
? SSH Public Key /Users/marcelobarbosa/.ssh/id_ed25519.pub
? Platform aws
INFO Credentials loaded from the "default" profile in file "/Users/marcelobarbosa/.aws/credentials" 
? Region eu-west-1
? Base Domain play.getchange.us
X Sorry, your reply was invalid: Value is required
? Cluster Name dev-cluster
? Pull Secret [? for help] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
INFO Creating infrastructure resources...         
INFO Waiting up to 20m0s for the Kubernetes API at https://api.dev-cluster.play.getchange.us:6443... 
INFO API v1.20.0+87cc9a4 up                       
INFO Waiting up to 30m0s for bootstrapping to complete... 
INFO Destroying the bootstrap resources...        
INFO Waiting up to 40m0s for the cluster at https://api.dev-cluster.play.getchange.us:6443 to initialize... 
INFO Waiting up to 10m0s for the openshift-console route to be created... 
INFO Install complete!                            
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/Users/marcelobarbosa/Documents/infrastructure-as-code/tmp/auth/kubeconfig' 
INFO Access the OpenShift web-console here: https://console-openshift-console.apps.dev-cluster.play.getchange.us 
INFO Login to the console with user: "kubeadmin", and password: "tQVCY-z7vRD-xqqw2-g6npm" 
INFO Time elapsed: 37m12s`

it will be nice if the rosa CLI can offer a parameter like to: `--basedomain` to deploy the cluster using this option.

**Comment by jharrington22** [comment]
Hi @marcelo-change installing a ROSA cluster on a custom base domain is not supported at this time. You can configure and use a custom domain/certificate for your application routes in OpenShift as a day 2 configuration once the cluster is installed see [here](https://access.redhat.com/articles/5599621).
