### ISSUE TITLE
`--output` cli arg only implemented on some commands

### ISSUE THREAD

**Issue by paulczar** [openshift/rosa#418]
I can use `rosa describe cluster --output json` but not `rosa create cluster --output json`  it would be great if this was a universal switch so my automation doesn't have to parse rosa output differently based on what actions are being performed.

**Comment by supernovae** [comment]
+1

**Comment by paulczar** [comment]
Just some followup its also inconsistent with the text output.  Example when I want to check if I'm pending OIDC via grep vs jq ...

```
❯ rosa describe cluster -c paul-test | grep State
State:                      pending (Waiting for OIDC configuration)

❯ rosa describe cluster -c paul-test --output json | jq .state
"pending"
```
