### ISSUE TITLE
JSON ouput for create admin

### ISSUE THREAD

**Issue by faermanj** [openshift/rosa#452]
The ```rosa create admin``` command should support the ```--output``` flag so that login can be automated without parsing the produced standard output.

**Comment by vkareh** [comment]
@faermanj - that's a good point. What would be a suitable output here? Would something like this work?
```json
{
  "url": "https://api.example.com:6443",
  "username": "cluster-admin",
  "password": "foo"
}
```
or do you have something else in mind?

**Comment by arendej** [comment]
captured as an enhancement
