### ISSUE TITLE
OIDC provider uses fixed region eu-east-1 

### ISSUE THREAD

**Issue by klaphi** [openshift/rosa#516]
Hi,

please enhance rosa in that way that the oidc provider for STS mode is using the default region or add the possibility to pass a region to `rosa create oidc-provider`.

In some companies not all AWS regions are allowed and if you provide a `--region` for creating a cluster it should be a consistent experience. 

In my case I am trying to deploy rosa to region `eu-central-1` but the OIDC provider seems to be hardcoded to region `eu-east-1`. 

I think there is no technical necessity for doing that because we are using the same configuration with EKS and there it works. 

Thanks

**Comment by vkareh** [comment]
The OIDC configuration public key is hosted in a Red Hat-owned S3 bucket, which happens to be located in `us-east-1`. We have it in our roadmap to either enable additional regions, or make it region-agnostic, which should solve your issue. Unfortunately we don't currently have a timeline for when this will be available.

**Comment by VictorChaizhv** [comment]
We also faced this problem while installing ROSA, where our AWS SCP only allow 'ap-southeast-1' region, we took more than 1 month to figure out.  While Redhat product team is trying to solve the problem, I strongly suggest that Redhat can publish these info on ROSA documentation, to avoid unnecessary frustration to customers

**Comment by arendej** [comment]
captured for docs improvement.
