### ISSUE TITLE
ROSA CLI 1.1.6 &  1.1.7 error "create_cluster_proxy"

### ISSUE THREAD

**Issue by IanScottIBM** [openshift/rosa#551]
Description
What problem/issue/behavior are you having trouble with?  What do you expect to see?
Downloaded ROSA CLI 1.1.6 to run on my mac (rosa-darwin-amd64 from https://github.com/openshift/rosa/releases)

I then tried to create a ROSA cluster using the new HTTP / HTTPS PROXY flags. This failed almost immediately with an error (see below):

Command:

./rosa-darwin-amd64 create cluster --private-link --multi-az --cluster-name=mydevrosa --machine-cidr=172.25.246.0/24 --subnet-ids=subnet-034f368cf97XXXXXX,subnet-0084b9e30c8XXXXXX,subnet-086ea2deeb2XXXXXX --enable-autoscaling --min-replicas 3 --max-replicas 6 --http-proxy http://proxy.ic.xxx.xxx:3128/ --https-proxy http://proxy.ic.xxx.xxx:3128/ --profile=my-dev-ocp

Output:

W: You are choosing to use AWS PrivateLink for your cluster. Once the cluster is created, this option cannot be changed.
? Are you sure you want to use AWS PrivateLink for cluster 'mydevrosa'? Yes
I: Creating cluster 'mydevrosa'
I: To view a list of clusters and their status, run 'rosa list clusters'

**E: Failed to create cluster: 'create_cluster_proxy' capability is not set for this organization**

I can't find any documentation on these new flag so I don't know what organization it is talking about. Also I am a bit worried that this new functionality  is trying to create a new proxy rather than using the one specified in the command-line.

Please can you explain how these are intended to work and if there are any additional environment of AWS settings required to be set...

These are previous issues I've raised relating to the use of proxies that I was hoping these new flag were added to fix...

Red Hat - Case 03011961 - Can't configure the "rosa" CLI tool to use a proxy
Red Hat - Case 03031217 - Cluster Wide noProxy setting is being ignored

Where are you experiencing the behavior? What environment?
Running 1.1.6  ROSA CLI from my MacOS laptop (OS 12.0.1)
[update: Running 1.1.7 ROSA CLI from my MacOS laptop (OS 12.1)

When does the behavior occur? Frequency? Repeatedly? At certain times?
Always

**Comment by arendej** [comment]
That was a feature gate. ROSA CLI 1.1.9 has un-gated the cluster proxy feature.

**Comment by IanScottIBM** [comment]
Hello @arendej is ROSA CLI 1.1.9 officially supported? I have just downloaded the CLI from the AWS console and it seems to still be 1.1.7...

**Comment by IanScottIBM** [comment]
Closing this ticket: I see v1.2.2 is now officially released and available on the AWS Console, so I'll try on that version.
