### ISSUE TITLE
Cluster admin account created via "rosa create admin" sometimes reports bad credentials

### ISSUE THREAD

**Issue by nastacio** [openshift/rosa#566]
This problem does not happen all the time, but when it happens, it is immediately after we create a new cluster with the `rosa` CLI.

We have automation that creates the new ROSA cluster via CLI, then waits for it to become ready, and finally requests the creation of the `cluster-admin` account.

The automation code uses the command `rosa describe cluster -c ${cluster_name} -o json ...` to wait for the cluster to be ready. It keeps checking the `state` field to return `ready`.

After that point, the automation issues the command to create the administrator account:

```
rosa create admin --cluster="${cluster_name}"
```

That command returns the `oc login` command for the new `cluster-admin` account, as expected:

```
W: It is recommended to add an identity provider to login to this cluster. See 'rosa create idp --help' for more information.
I: Admin account has been added to cluster '...'.
I: Please securely store this generated password. If you lose this password you can delete and recreate the cluster admin user.
I: To login, run the following command:

   oc login https://api....openshiftapps.com:6443 --username cluster-admin --password ...

I: It may take up to a minute for the account to become active.
```

Most of the time (80%, perhaps,) that `oc login` commands works as expected, but some other 20% of the time, it returns an error:

```
oc login https://api....openshiftapps.com:6443 --username cluster-admin --password ...
Login failed (401 Unauthorized)
Verify you have provided correct credentials.
```

When the problem happens, we often run the `oc login...` command 20-60 minutes later and still get the "401" error, so we don't think the problem is not waiting long enough.

Deleting the account and recreating it fixes the problem without fail, and it takes only a few seconds for the `cluster-admin` account to become available.

**Comment by nastacio** [comment]
@shankarpentyala07, If you haven't done it already, I suggest you reset your cluster credentials immediately.

**Comment by shankarpentyala07** [comment]
Thanks @nastacio for the headsup, I have deleted the cluster, 
Were you able to find any workaround for this issue?

**Comment by nastacio** [comment]
> Were you able to find any workaround for this issue?

The only workaround I have is the one listed in the description.

I have not seen that problem in a long while, so maybe they fixed it indirectly through some other issue.

**Comment by shankarpentyala07** [comment]
I did hit this issue again in our Jenkins Build , The rosa version is 4.10.15

**Comment by shankarpentyala07** [comment]
For reference:
Below is the info i got from support team:

The rosa create admin command changes the OAuth configuration of the cluster, which automatically moves the authentication cluster operator to progressing state. It redeploys the oauth-openshift pods in the openshift-authentication namespace. There is no determined time for these tasks to complete; however, as soon as the oauth-openshift pods are rescheduled and the old ones terminated, the authentication should work.

One thing that you could do is to add a longer wait time after the admin user is created and they test the logi

Adding wait time works , the  sample script logic be:
#!/bin/bash
login_cmd=$1
login_state="Failed"
counter=0
while [[ $counter  -lt 20 && $login_state == "Failed" ]]; do
    sleep 60
    counter=$(( counter + 1 ))
    echo -e "\n Login to rosa cluster as cluster-admin"
    $login_cmd --insecure-skip-tls-verify
    if [  $? == 0 ]; then
    login_state="Success"
    fi       
done
