### ISSUE TITLE
`rosa install addon ...` non-interactive install

### ISSUE THREAD

**Issue by jbpratt** [openshift/rosa#629]
Hi! Is there currently a way to perform add-on installation in a non-interactive way? I'm being prompted for the parameters required:
```
❯ rosa install addon cluster-logging-operator -c test --yes
? Use AWS CloudWatch: No
? Collect Applications logs: No
? Collect Infrastructure logs: No
? Collect Audit logs (optional): No
? CloudWatch region (optional):
```

**Comment by jbpratt** [comment]
Found the code related to this, I assume I am able to set the parameters dynamically as flags 
https://github.com/openshift/rosa/blob/e75f60f5a143fccf008325cf6e17aa6fcb6b9a23/cmd/install/addon/cmd.go#L144-L147

**Comment by holyspectral** [comment]
For others happened to run into this, you can use `rosa describe addon cluster-logging-operator` to check add-on's parameters.
