### ISSUE TITLE
Use of path in rosa account roles

### ISSUE THREAD

**Issue by manaveen** [openshift/rosa#718]
Hi Team,
ROSA installer is able to get the role name after role: element in ARN. However, the installer is failing to get the role name whilst using a path in Role ARN.

For Example, ROSA installer gets role name from Role ARN arn:aws:iam::XXXXXXXXXXXX:role/ManagedOpenShift-Installer-Role. But, installer is failing to get role name from Role ARN arn:aws:iam::XXXXXXXXXXXX:role/app/ManagedOpenShift-Installer-Role and looking for a role with the name 'app'

**Comment by acathrow** [comment]
This change is in process, rough eta mid July
