### ISSUE TITLE
Need to add arm64/aarch64 linux builds

### ISSUE THREAD

**Issue by ausil** [openshift/rosa#874]
As the Arm architecture becomes more prevalent, there is a need to run the binaries on Linux currently, there are only amd64 builds available

**Comment by iamkirkbater** [comment]
+1 to this please

**Comment by iamkirkbater** [comment]
This issue is still outstanding.

**Comment by iamkirkbater** [comment]
Ahh, nice, I see it was added back in https://github.com/openshift/rosa/releases/tag/v1.2.27. 

If you want to keep this open for the openshift downloads page that's fine, it would be a better experience for customers to have a unified place to download their tooling, but for my team's and my needs I'm satisfied with the github releases.

**Comment by kami619** [comment]
+1 @iamkirkbater I reached this issue, looking for a arm build to run from my M1 Mac. It would be nice to update the downloads page as well, for better customer UX.
