### ISSUE TITLE
pre-flight check for checking NAT gateways is missing

### ISSUE THREAD

**Issue by spaparaju** [openshift/rosa#906]
rosa version `1.2.8`

For private clusters with private-link, rosa accepts private subnet IDs, results in cluster creation error (after 30 minutes into the cluster creation) and an email to the customer if NAT gateways are missing from the public subnets of the respective VPC.

**Comment by spaparaju** [comment]
This problem is reproducible on public ROSA clusters as well.

**Comment by oriAdler** [comment]
Hey @spaparaju, can you please share the cluster ID? 
The cluster spec with more details? and the error message from the email.
That seems to be a problem with the AWS network configuration.
Thanks
