### ISSUE TITLE
Automate life cycling of ROSA clusters

### ISSUE THREAD

**Issue by spaparaju** [openshift/rosa#911]
rosa version `1.2.8`

Users would like to automate ROSA cluster life cycling (create/edit/delete) from the current state of things which is manually create cluster either at  RH Console / ROSA cmdLine. 

To automate life cycling ROSA clusters, it would be nice if-

- there is an ROSA API that users can leverage and associated documentation
- as simple as `rosa any-cmd cluster -o json/yaml` to write automation on a structured format

**Comment by igoihman** [comment]
Hi @spaparaju please visit our project https://github.com/openshift-online/terraform-provider-ocm
You can also use the following API in order to create ROSA clusters (after creating account roles)
```
ocm post /api/clusters_mgmt/clusters --body <cluster_spec>

{
 "aws": {
        "sts": {
            "auto_mode": false,
            "instance_iam_roles": {
                "master_role_arn": "arn:aws:iam::<aws_account_id>:role/<role_prefix>-ControlPlane-Role",
                "worker_role_arn": "arn:aws:iam::<aws_account_id>:role/<role_prefix>-Worker-Role"
            },
            "operator_role_prefix":"<cluster_name>-<four_random_characters>",
            "role_arn": "arn:aws:iam::<aws_account_id>:role/<role_prefix>-Installer-Role",
            "support_role_arn": "arn:aws:iam::<aws_account_id>:role/<role_prefix>-Support-Role"
        },
        "account_id": "<aws_account_id>"
    },
    "ccs": {
        "enabled": true
    },
   "product": {
        "kind": "Product",
        "id": "rosa"
    },
    "region": {
    "id": "<cluster_region>"
  },
    "properties":{
        "rosa_creator_arn":"<user_arn>"
    },
    "name": "<cluster_name>"
 }

```
A cluster will be created in `waiting` mode, then run the following commands in order to start installation
```
$ rosa create operator-roles cluster -c <cluster_name>

$  rosa create oidc-provider cluster -c <cluster_name>
```
